project_id = "kcihftfgmsrpcljsbjdj"

[functions.firecrawl-scrape]
verify_jwt = false

[functions.firecrawl-search]
verify_jwt = false

[functions.firecrawl-map]
verify_jwt = false

[functions.1688-search]
verify_jwt = false

[functions.1688-item-get]
verify_jwt = false
